//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------

namespace AcademicLeaveSystem
{
    public partial class Login
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.Button btnLogin;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
