//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------

namespace AcademicLeaveSystem
{
    public partial class Main
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblWelcome;

        protected global::System.Web.UI.WebControls.Calendar calAcademic;

        protected global::System.Web.UI.WebControls.Label lblDate;

        protected global::System.Web.UI.WebControls.TextBox txtLeaveDate;

        protected global::System.Web.UI.WebControls.TextBox txtReason;

        protected global::System.Web.UI.WebControls.RadioButtonList rblLeaveType;

        protected global::System.Web.UI.WebControls.Button btnApply;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.GridView gvLeave;

        protected global::System.Web.UI.WebControls.Button btnLogout;
    }
}
